minVersion: 0.23.1
changelogPolicy: auto
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: npm
    id: 'whatever :)'
  - name: github
    includeNames: /^sentry-.*$/
