minVersion: 0.23.1
changelogPolicy: auto
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  # Purposefully deactivating npm target to test diverging craft configs
  # - name: npm
  - name: github
    includeNames: /^sentry-.*$/
